# Environment variables
# PUSHBACK_TOKEN: Personal access token from Github, needs repo access: https://github.com/settings/tokens
# PUSHBACK_USER_EMAIL: Email of the user profile used as autobot
# PUSHBACK_USER_NAME: Github user name used as autobot
version: 2
machine:
  timezone: Europe/Helsinki
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.4-node
    steps:
      - checkout
      - run:
          name: Setup git
          command: |
            git remote add pushback https://$PUSHBACK_TOKEN@github.com/janivihervas/playground.git
            git config --global user.name $PUSHBACK_USER_NAME
            git config --global user.email $PUSHBACK_USER_EMAIL
      - restore_cache:
          keys:
            - v1-deps-{{ arch }}-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
      - run:
          name: Install
          command: |
            if [[ $CIRCLE_BRANCH != "master" ]]; then
              make install-update
              if [[ $(git status --porcelain) ]]; then
                git add --all
                git commit -m "AUTOMATIC BOT: Install"
              fi
            else
              make install
            fi
      - save_cache:
          key: v1-deps-{{ arch }}-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - run:
          name: make format
          command: |
            if [[ $CIRCLE_BRANCH != "master" ]]; then
              make format
              if [[ $(git status --porcelain) ]]; then
                git add --all
                git commit -m "AUTOBOT: Format"
              fi
            fi
      - run:
          name: Format Markdown
          command: |
            if [[ $CIRCLE_BRANCH != "master" ]]; then
              sudo npm install -g prettier@1.14.0 markdown-toc@1.2.0
              find . -type f -name "*.md" | parallel -k 'markdown-toc -i "{}"'
              prettier --write "**/*.md"
              if [[ $(git status --porcelain) ]]; then
                git add --all
                git commit -m "AUTOBOT: Format Markdown"
              fi
            fi
      - run: make lint
      - run: make test-codecov
      - run: make build
      - run:
          name: Push autobot changes
          command: |
            if [[ $CIRCLE_BRANCH != "master" ]]; then
              if [[ $(git log origin/$CIRCLE_BRANCH..$CIRCLE_BRANCH) ]]; then
                echo "Pushing autobot fixes"
                git push --set-upstream pushback $CIRCLE_BRANCH
                exit 1
              fi
            fi
